image: keymetrics/pm2:latest-slim

stages:
  - deploy

deploy_prod:
  stage: deploy
  script:
    - apt-get -qq update && apt-get -qq -y install openssh-client git
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
    - pm2 deploy ecosystem.config.js production
  only:
  - main
